### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by Jason-Cooke**

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for catching the typo Jason. I'm going to change the wording to "environment" instead of "environmental".

**Comment by alexellis** [comment]
How did you find the tool? Have you had a go with it yet?

**Comment by Jason-Cooke** [comment]
You're welcome Alexellis. 

I have not experimented with this tool yet.

**Comment by alexellis** [comment]
Curious how you decided to send a PR? Do you have a bot that searches public repos for typos?

**Comment by Jason-Cooke** [comment]
Spot on! I wrote a little script that does exactly that :)

**Pull request closed without merging**
